### ISSUE TITLE
ios saveImage(storeImage) directory issue

### ISSUE THREAD

**Issue by lovelyelfpop** [RaananW/PhoneGap-Image-Resizer#20]
when the option "directory" is a file URL(start with "file://") on ios, the storeImage(saveImage) function failed.

add this line after "NSString *directory =  [options objectForKey:@"directory"];" inside the "saveImage" function:

"directory = [self getUrl:directory];"

**Comment by RaananW** [comment]
Hi, thanks. Looks like you find a fix already! :-)
If you tested it and it works - care to send a PR?

**Comment by RaananW** [comment]
PR merged, https://github.com/RaananW/PhoneGap-Image-Resizer/pull/21
