### ISSUE TITLE
getImageSize returns 0

### ISSUE THREAD

**Issue by efen800** [RaananW/PhoneGap-Image-Resizer#9]
I installed the plugin using CLI and called the function as
window.imageResizer.getImageSize(function(rep){console.log(rep)},function(rep){console.log("error");},uri,{imageType:"IMAGE_DATA_TYPE_URL"})
uri begins with file:/// (and tried without it) 
Whatever I do, plugin returns 0 for height and width.

I am running it on IOS simulator and using phone gap 3.5. 

Do you have any idea? 

On Readme file there is a quirk mentions about Base64 Encoder/Decoder, is it related to that? It seems that, plugin already have these files. Should I run another code before it?

**Comment by RaananW** [comment]
There was a problem with data type url , https://github.com/RaananW/PhoneGap-Image-Resizer/commit/f9d6d653681527c949cc25a1ee565c9f9680bf4e has probably fixed it. Want to try and let me know if it works now?

**Comment by RaananW** [comment]
Closing as no answer received, please reopen if it is still happening.
